"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e
"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        numdictA = dict()
        numdictB = dict()
        
        for letter in s:
            if letter in numdictA:
                numdictA[letter]+=1
            else:
                numdictA[letter] = 1
        for letter in t:
            if letter in numdictB:
                numdictB[letter]+=1
            else:
                numdictB[letter] = 1
        for key in numdictB:
            if key not in numdictA:
                return key
        for key in numdictB:
            if numdictB[key] != numdictA[key]:
                return key

# test
s = Solution()
str1 = "abcde"
t1 = "decbaf"

str2 = "aab"
t2 = "abaa"

res1 = s.findTheDifference(str1, t1)
res2 = s.findTheDifference(str2, t2)

print (res1, res2)
